### PR TITLE
Fix SSR onDestroy - ensure document before calling removeEventListener

### LINKED ISSUE #36: Error during SSR due to `onDestroy` / `cleanEvents` being called
Error during SSR due to `cleanEvents` being called.

- Provide the steps to reproduce the issue, e.g.:

  1.  Create a svelte-kit page containing `Cropper` component 
  2.  Somehow destroy/move that component to a different location during SSR (for example, in my specific use case, the `Cropper` component exists in a modal div that needs to be appended to the document root)
  3. `onDestroy()` fires which calls `cleanEvents()`, resulting in a `document is not defined` error when attempting to remove the event listeners.

`onDestroy` firing during SSR is expected behaviour, see https://github.com/sveltejs/kit/issues/945

I'll raise a PR to offer a fix for the issue :slightly_smiling_face: 

```log
[svelte] ReferenceError: document is not defined
[svelte]     at cleanEvents (/node_modules/svelte-easy-crop/src/index.svelte:61:3)
[svelte]     at eval (/node_modules/svelte-easy-crop/src/index.svelte:57:3)
[svelte]     at run (/node_modules/svelte/internal/index.mjs:20:12)
[svelte]     at Array.forEach (<anonymous>)
[svelte]     at run_all (/node_modules/svelte/internal/index.mjs:26:9)
[svelte]     at Object.render (/node_modules/svelte/internal/index.mjs:1882:13)
[svelte]     at render_response (file:///home/oscarhermoso/Git/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:119:27)
[svelte]     at runMicrotasks (<anonymous>)
[svelte]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[svelte]     at async render_page (file:///home/oscarhermoso/Git/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:277:10)
```

### PR DESCRIPTION
**Pull request by oscarhermoso**
Closes #36

### CODE REVIEW

**Review by ValentinH — APPROVED** [review]

File: src/index.svelte [hunk 1]
```diff
@@ -40,10 +40,12 @@
   })
 
   const cleanEvents = () => {
-    document.removeEventListener('mousemove', onMouseMove)
-    document.removeEventListener('mouseup', onDragStopped)
-    document.removeEventListener('touchmove', onTouchMove)
-    document.removeEventListener('touchend', onDragStopped)
+    if (document) {
```
Comment (ValentinH) [inline src/index.svelte:43]: You might want to even do `typeof document !== 'undefined'` actually because accessing the variable could even fail.

Comment (oscarhermoso) [reply src/index.svelte]: Cheers, amended the commit

**Review by ValentinH — APPROVED** [review]

**Comment by ValentinH** [comment]
Thanks for the fix!

This was released as https://github.com/ValentinH/svelte-easy-crop/releases/tag/v1.0.8
